### ISSUE TITLE
getCountry() cause internal error

### ISSUE THREAD

**Issue by danteYuX** [DivanteLtd/coreshop-vsbridge#17]
in ResponseBodyCreator.php -> getAddress function
`$address['country_id'] = $defaultAddress->getCountry() `
is not an array but an object, which causes an internal error.
I think, the right solution is:
`$address['country_id'] = $defaultAddress->getCountry()->getId();`

**Comment by kwreczycki** [comment]
@danteYuX Correct, could you prepare PR for this ?

**Comment by danteYuX** [comment]
Of course I do it very well.

**Comment by kwreczycki** [comment]
@danteYuX Just create PR to master
